import { useState } from 'react';
import { ethers } from 'ethers';
import deployedContracts from "../contracts/hardhat_contracts.json";
import { Account, Contract, GasGauge, Header, Ramp, ThemeSwitch, SketchComp } from "../components";

const genfrensContract = "0x37263092Ea7E55439dE4Efce651916B0b96eB7aD";

let params = (new URL(document.location)).searchParams;
let tokenId = parseInt(params.get("token"));


const Home = () => {

    async function requestAccount() {
        await window.ethereum.request({ method: 'eth_requestAccounts' });
    }

    return (
        <div className="home">
            <div className="container align-items-start" id="Main">
                <div className="pt-2" id="Info">
                    <SketchComp />
                    <h2>GenFrens</h2>
                    <p className="px-2">There are 444 GenFrens looking for new pals on Ethereum mainnet. Genfrens are are generated on mint with the traits and code which creates them mirrored on chain permanently. Your GenFrens will never turn your back on you.</p>
                    <p className="px-2">Circolors community members are building an ecosystem to help onboard new devs and give people interesting projects to work on to strengthen their portfolios.</p>
                    <br />
                    <h2>Circolors</h2>
                    <p className="px-2">Circolors is a Discord community for aspring generative artists, web3 developers, NFT apes and shitposters to share ideas and combine their strengths into becoming a Web3 superpower.  </p>
                    <p className="px-2">GenFrens is the first on-chain project from within the Circolors community, but expect more to follow in the near future.</p>
                </div>
                <br />
                <div className="pb-2 text-secondary" id="Airdrop">
                    <h2>Project details</h2>
                    <span className="getDrop p-4">Collection Size: 444 frens</span><br />
                    <span className="getDrop p-4">Mint Price: 0.01eth</span><br />
                    <span className="getDrop p-4">Each genfren is unique and generated by code using p5js.</span><br />
                    <span className="getDrop p-4">GenFren's traits and code are permanently mirrored on chain.</span><br />
                    <span className="getDrop p-4">50% of the funds raised by the GenFrens mint will be retained by the Circolors community to build its Generative Art collection and help bootstrap future Circolors projects.</span>
                </div>

            </div>
        </div>




    );
}

export default Home;